- name: install util packages
  apt: name={{ item }} state=present
  with_items:
    - htop
    - vim
    - curl
    - wget
    - nload
    - tcpdump

- name: change motd
  template: src=motd dest=/etc/motd
