- name: install htop
  apt: name=htop state=present
- name: install vim
  apt: name=vim state=present
- name: install mtr
  apt: name=mtr-tiny state=present
- name:  install curl
  apt: name=curl state=present
- name: install wget
  apt: name=wget state=present
- name: install nload
  apt: name=nload state=present
- name: install tcpdump
  apt: name=tcpdump state=present
