- name: install util packages
  apt: name={{ item }} state=present update_cache=yes
  with_items:
    - htop
    - vim
    - curl
    - wget
    - nload
    - tcpdump
    - nmap

- name: change motd
  template: src=motd dest=/etc/motd
